// <auto-generated />
namespace AdsBoard.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Removedheaderinad : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Removedheaderinad));
        
        string IMigrationMetadata.Id
        {
            get { return "202202031523124_Removed header in ad"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
