// <auto-generated />
namespace AdsBoard.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class changepricetype2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changepricetype2));
        
        string IMigrationMetadata.Id
        {
            get { return "202201301546067_change price type #2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
